export const projects = [
  {
    title: "Weather app",
    description: "Application that allows us to see the weather of different cities plus its forecast for the following days",
      image: '/images/weather.gif',
      tags: [ 'React', "Hooks", "Storybook", "Testing", "Three", "reCharts" ],
    source: 'https://weather-app-2022a.netlify.app',
    visit: 'https://github.com/amarismariano/weather-app-2022',
    id: 0,
  },
  {
    title: "Loan App ",
    description: "A simple application that allows us to evaluate how much money we can borrow with a fixed term plus monthly payments",
      image: '/images/loan.gif',
      tags: [ 'React', "Hooks" ],
    source: 'https://cotizador-app-1.netlify.app',
    visit: 'https://github.com/amarismariano/cotizador-app',
    id: 1,
  },
  {
    title: "Add Users ",
    description: "A simple app that I used as a way to learn React hooks that allow us to add and remove users to a list.",
      image: '/images/add-user.gif',
      tags: [ 'React', "Hooks" ],
    source: 'https://add-users-appss.netlify.app',
    visit: 'https://github.com/amarismariano/addUsers-app',
    id: 2,
  },
  {
    title: "Expenses ",
    description: "An application that helps us to have a history of our expenses throughout the month and tells us in which months we have spent the most",
      image: '/images/expenses2.gif',
      tags: [ 'React', "Hooks" ],
    source: 'https://expenses-app1.netlify.app',
    visit: 'https://github.com/amarismariano/expenses-app',
    id: 3,
  },
  {
    title: "Bloc de Notas ",
    description: "An application that allows us to create personal notes or to follow up on something we are doing, it was an application that I made when I finished my Udemy course",
      image: '/images/bloc.gif',
      tags: [ 'React' , "Hooks"],
    source: 'https://blockdenotas1.netlify.app',
    visit: 'https://github.com/amarismariano/BlocDeNotas',
    id: 4,
  },
  {
    title: 'Linkedin clone',
    description:"",
    image: '/images/linkedin2.png',
    tags: ['React', 'JavaScript', "Material-UI", "Redux", "Firebase"],
    source: 'https://linkedinclone123a.netlify.app',
    visit: 'https://github.com/amarismariano/linkedinclone1',
    id: 5,
  },
  {
    title: 'Netflix clone',
    description: "",
      image: '/images/netflix2.jpg',
      tags: ['React', 'Redux', "Firebase", "Axios"],
    source: 'https://netflixclonesss.netlify.app',
    visit: 'https://github.com/amarismariano/netflix-clone',
    id: 6,
  },
  {
    title: 'Gmail clone',
    description: "",
    image: '/images/gmail.png',
    tags: ['React', 'Material-UI', "Firebase", "Hooks"],
    source: 'https://gmail-amarisdev.netlify.app',
    visit: 'https://github.com/amarismariano/gmail-clone',
    id: 7,
  },
  {
    title: 'Slack clone',
    description: "",
    image: '/images/slack.png',
    tags: ['React', 'Material-UI', 'Redux', "Firebase", "React-SC"],
    source: 'https://slackappclone.netlify.app',
    visit: 'https://github.com/amarismariano/slackclone',
    id: 8,
  }
];

export const TimeLineData = [
  { year: "", text: 'Law School at Fundacion Universitaria del Area Andina', },
  { year: "", text: 'Full Stack Developer Course at Udemy', },
  { year: "", text: 'Web Responsive Design Course and Several Courses at FreeCodeCamp' },
  { year: "", text: 'Back-end Development Course at Udemy', },
  { year: "", text: 'Advanced React Course at Udemy' }
];